version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "4000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app        # live reload під час розробки
    command: "npm run dev"
